### ISSUE TITLE
`source` paths interpreted as string

### ISSUE THREAD

**Issue by marcomow** [fabasoad/translation-action#141]
```
source: rules/en.md
```
will translate the text `rules/en.md` and not the content of the file in the specified path

**Comment by fabasoad** [comment]
I've added some tests to be sure that this parameter works as expected. The [latest run](https://github.com/fabasoad/translation-action/actions/runs/7517021793) passes successfully. Please be sure that `rules/en.md` file exists. Also, I've added some debug logs - could you try to re-run your pipeline on a latest version of this GHA with debug enabled? You should see logs something like:

```text
##[debug]rules/en.md file exists. Reading from file...
##[debug]File content: <your content here>
```

or this (in case it does not work as expected):

```text
##[debug]rules/en.md file does not exist. "rules/en.md" will be translated
```
